name: CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be execution (login ou search)'
        required: false
        default: ''

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
      - name: Install dependencies
        run: mvn install
      - name: Run tests
        run: |
          TAG_ESPECIFIC=${{ github.event.inputs.tag }}
          TAG_EXECUTION="${{ (github.event.inputs.tag && '@' || '') }}$TAG_ESPECIFIC" 

          echo "this tag execution: $TAG_EXECUTION"

          mvn test -Dcucumber.options="$TAG_EXECUTION" 
        env:
          TIMEOUT_SECONDS: 30
