name: CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be execute (login or search)'
        required: false
        default: ''

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [''] 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Setup Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
      - name: Install dependencies
        run: mvn install
      - name: Run tests
        run: |
          TAG_ESPECIFIC=${{ github.event.inputs.tag || matrix.tag }} # Usa a tag da entrada ou da matriz
          TAG_EXECUTION="${{ (github.event.inputs.tag || matrix.tag) && '@' || '' }}$TAG_ESPECIFIC"
          echo "Execute tests with the tag: $TAG_EXECUTION"
          mvn test -Dcucumber.options="$TAG_EXECUTION"
      - name: Package application
        run: mvn package
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: application-artifact 
          path: target/*.jar
          TIMEOUT_SECONDS: 30
